using DevExpress.Xpf.DemoBase;
using SchedulingDemo.ViewModels;

namespace SchedulingDemo {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/WindowsCustomization/WindowsCustomizationDemoModule.xaml",
        "Modules/WindowsCustomization/CustomAppointmentWindow.xaml",
        "ViewModels/WindowsCustomization/WindowsCustomizationDemoViewModel.(cs)")]
    public partial class WindowsCustomizationDemoModule : SchedulingDemoModule {
        public WindowsCustomizationDemoModule() {
            InitializeComponent();
        }

        private void OnTimeRulerWindowShowing(object sender, DevExpress.Xpf.Scheduling.TimeRulerWindowShowingEventArgs e) {
            e.Window.DataContext = new CustomTimeRulerWindowViewModel(e.TimeRuler, this.scheduler.TimeZone);
        }
    }
}
