using System.Windows.Controls;
using DevExpress.Xpf.DemoBase;

namespace SchedulingDemo {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/AboutView.xaml",
        "ViewModels/LinksViewModel.(cs)")]
    public partial class AboutView : UserControl {
        public AboutView() {
            InitializeComponent();
        }
    }
}
