Imports DevExpress.Xpf.DemoBase

Namespace ControlsDemo.TabControl.ColorizedTabs
    <NoAutogeneratedCodeFiles, CodeFiles("Modules/TabControl.ColorizedTabs/MainView.xaml", "Modules/TabControl.ColorizedTabs/MainViewModel.(cs)")>
    Partial Public Class MainView
        Inherits ControlsDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
