Imports DevExpress.Xpf.DemoBase
Imports DevExpress.Xpf.Ribbon

Namespace RibbonDemo
    <NoAutogeneratedCodeFiles>
    Public Class RibbonOffice2007
        Inherits RibbonSimplePad

        Public Sub New()
        End Sub
        Protected Overrides Function GetRibbonStyle() As RibbonStyle
            Return RibbonStyle.Office2007
        End Function
    End Class
End Namespace
