Imports MVVMDemo.Services
Imports System
Imports DevExpress.Xpf.DemoBase

Namespace MVVMDemo
    Partial Public Class ServicesModule
        Inherits MVVMDemoModule

        Protected Overrides Function CreateShowcases() As ShowcaseInfo()
            Const path As String = "Modules/Services"
            Return New ShowcaseInfo() { LoadShowcase("IMessageBoxService", "113933/MVVM-Framework/Services/Predefined-Set/Message-Box-Services", path, { GetType(MessageBoxServiceViewModel), GetType(MessageBoxServiceView) }), LoadShowcase("IDialogService", "113932/MVVM-Framework/Services/Predefined-Set/Dialog-Services", path, { GetType(DialogServiceViewModel), GetType(DialogServiceDetailViewModel), GetType(DialogServiceView) }), LoadShowcase("IWindowService + ICurrentWindowService", Nothing, path, { GetType(WindowServiceViewModel), GetType(WindowServiceDetailViewModel), GetType(WindowServiceView) }), LoadShowcase("INavigationService ", "113944/MVVM-Framework/Services/Predefined-Set/FrameNavigationService", path & "/NavigationService", { GetType(Services.Navigation.FrameView), GetType(Services.Navigation.NavigationDetailView), GetType(Services.Navigation.CollectionViewModel), GetType(Services.Navigation.DetailViewModel)}), LoadShowcase("IDocumentManagerService - Tabbed MDI View", "18173/MVVM-Framework/Services/Predefined-Set/Document-Services/TabbedDocumentUIService", path & "/DocumentManagerService", GetDocumentServiceTypes(GetType(Services.DocumentManager.TabbedView))), LoadShowcase("IDocumentManagerService - Windows View", "18174/MVVM-Framework/Services/Predefined-Set/Document-Services/WindowedDocumentUIService", path & "/DocumentManagerService", GetDocumentServiceTypes(GetType(Services.DocumentManager.WindowedView))), LoadShowcase("IDocumentManagerService - Navigation Frame View", "18172/MVVM-Framework/Services/Predefined-Set/Document-Services/FrameDocumentUIService", path & "/DocumentManagerService", GetDocumentServiceTypes(GetType(Services.DocumentManager.FrameView))), LoadShowcase("IDocumentManagerService - Docking View", "18275/MVVM-Framework/Services/Predefined-Set/Document-Services/DockingDocumentUIService", path & "/DocumentManagerService", GetDocumentServiceTypes(GetType(Services.DocumentManager.DockingView))), LoadShowcase("IDispatcherService", "113861/MVVM-Framework/Services/Predefined-Set/DispatcherService", path, { GetType(DispatcherServiceViewModel), GetType(DispatcherServiceView) }), LoadShowcase("IOpenFileDialogService", "114757/MVVM-Framework/Services/Predefined-Set/OpenFileDialogService", path, { GetType(OpenFileDialogServiceViewModel), GetType(OpenFileDialogServiceView) }), LoadShowcase("ISaveFileDialogService", "114760/MVVM-Framework/Services/Predefined-Set/SaveFileDialogService", path, { GetType(SaveFileDialogServiceViewModel), GetType(SaveFileDialogServiceView) }), LoadShowcase("IFolderBrowserDialogService", "114755/MVVM-Framework/Services/Predefined-Set/FolderBrowserDialogService", path, { GetType(FolderBrowserDialogServiceViewModel), GetType(FolderBrowserDialogServiceView) }), LoadShowcase("Implementing a Custom Service", "16920/MVVM-Framework/Services/How-to-create-a-Custom-Service", path, { GetType(CustomServiceViewModel), GetType(GridExportService), GetType(CustomServiceView) })}
        End Function
        Private Shared Function GetDocumentServiceTypes(ByVal viewType As Type) As Type()
            Return { viewType, GetType(Services.DocumentManager.CollectionView), GetType(Services.DocumentManager.DocumentDetailView), GetType(Services.DocumentManager.CollectionViewModel), GetType(Services.DocumentManager.DetailViewModel) }
        End Function
    End Class
End Namespace
