Imports DevExpress.Xpf.DemoBase
Imports SchedulingDemo.ViewModels

Namespace SchedulingDemo
    <NoAutogeneratedCodeFiles, CodeFiles("Modules/WindowsCustomization/WindowsCustomizationDemoModule.xaml", "Modules/WindowsCustomization/CustomAppointmentWindow.xaml", "ViewModels/WindowsCustomization/WindowsCustomizationDemoViewModel.(cs)")>
    Partial Public Class WindowsCustomizationDemoModule
        Inherits SchedulingDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub

        Private Sub OnTimeRulerWindowShowing(ByVal sender As Object, ByVal e As DevExpress.Xpf.Scheduling.TimeRulerWindowShowingEventArgs)
            e.Window.DataContext = New CustomTimeRulerWindowViewModel(e.TimeRuler, Me.scheduler.TimeZone)
        End Sub
    End Class
End Namespace
