Imports DevExpress.Xpf.DemoBase

Namespace SchedulingDemo
    <NoAutogeneratedCodeFiles, CodeFiles("Modules/AppointmentCustomizationDemoModule.xaml", "ViewModels/AppointmentCustomizationDemoViewModel.(cs)")>
    Partial Public Class AppointmentCustomizationDemoModule
        Inherits SchedulingDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
