Imports DevExpress.Xpf.DemoBase

Namespace SchedulingDemo
    <NoAutogeneratedCodeFiles, CodeFiles("Modules/DayViewPerformanceDemoModule.xaml", "ViewModels/DayViewPerformanceDemoViewModel.(cs)")>
    Partial Public Class DayViewPerformanceDemoModule
        Inherits SchedulingDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
