Imports DevExpress.Xpf.DemoBase

Namespace SchedulingDemo
    <NoAutogeneratedCodeFiles, CodeFiles("Modules/EndUserRestrictionsDemoModule.xaml", "Modules/EndUserRestrictionsDemoModule.xaml.(cs)", "ViewModels/EndUserRestrictionsDemoViewModel.(cs)")>
    Partial Public Class EndUserRestrictionsDemoModule
        Inherits SchedulingDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
