Imports DevExpress.Xpf.DemoBase

Namespace SchedulingDemo
    <NoAutogeneratedCodeFiles, CodeFiles("Modules/MonthViewDemoModule.xaml", "ViewModels/MonthViewDemoViewModel.(cs)")>
    Partial Public Class MonthViewDemoModule
        Inherits SchedulingDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
