Imports DevExpress.Xpf.DemoBase

Namespace SchedulingDemo
    <NoAutogeneratedCodeFiles, CodeFiles("Modules/MonthViewPerformanceDemoModule.xaml", "ViewModels/MonthViewPerformanceDemoViewModel.(cs)")>
    Partial Public Class MonthViewPerformanceDemoModule
        Inherits SchedulingDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
