Imports DevExpress.Xpf.DemoBase

Namespace SchedulingDemo
    <NoAutogeneratedCodeFiles, CodeFiles("Modules/TimeRulerDemoModule.xaml", "ViewModels/TimeRulerDemoViewModel.(cs)")>
    Partial Public Class TimeRulerDemoModule
        Inherits SchedulingDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
