Imports DevExpress.Xpf.Core
Imports DevExpress.Xpf.DemoBase

Namespace SchedulingDemo
    <NoAutogeneratedCodeFiles, CodeFiles("Modules/TimelineViewDemoModule.xaml", "ViewModels/TimelineViewDemoViewModel.(cs)")>
    Partial Public Class TimelineViewDemoModule
        Inherits SchedulingDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
