Imports DevExpress.Xpf.Core
Imports DevExpress.Xpf.DemoBase

Namespace SchedulingDemo
    <NoAutogeneratedCodeFiles, CodeFiles("Modules/TimelineViewPerformanceDemoModule.xaml", "ViewModels/TimelineViewPerformanceDemoViewModel.(cs)")>
    Partial Public Class TimelineViewPerformanceDemoModule
        Inherits SchedulingDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
