Imports DevExpress.Xpf.Core
Imports DevExpress.Xpf.DemoBase

Namespace SchedulingDemo
    <NoAutogeneratedCodeFiles, CodeFiles("Modules/TimelineScalesDemoModule.xaml", "ViewModels/TimelineScalesDemoViewModel.(cs)")>
    Partial Public Class TimelineScalesDemoModule
        Inherits SchedulingDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
