Imports DevExpress.Xpf.DemoBase

Namespace SchedulingDemo
    <NoAutogeneratedCodeFiles, CodeFiles("Modules/WeekViewDemoModule.xaml", "ViewModels/WeekViewDemoViewModel.(cs)")>
    Partial Public Class WeekViewDemoModule
        Inherits SchedulingDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
