Imports DevExpress.Xpf.DemoBase

Namespace SchedulingDemo
    <NoAutogeneratedCodeFiles, CodeFiles("Modules/WorkWeekViewDemoModule.xaml", "ViewModels/WorkWeekViewDemoViewModel.(cs)")>
    Partial Public Class WorkWeekViewDemoModule
        Inherits SchedulingDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
