Imports DevExpress.Xpf.DemoBase

Namespace RibbonDemo
    <NoAutogeneratedCodeFiles>
    Public Class RibbonOffice2010
        Inherits RibbonSimplePad

        Public Sub New()
        End Sub
    End Class
End Namespace
