using System;
using DevExpress.Xpf.Charts;
using DevExpress.Xpf.DemoBase;

namespace ChartsDemo {
    [NoAutogeneratedCodeFiles]
    [CodeFile("Modules/XyzChart/Bubble3DSeriesView.xaml"),
    CodeFile("Modules/XyzChart/Bubble3DSeriesView.xaml.(cs)")]
    public partial class Bubble3DSeriesView : ChartsDemoModule {
        public Bubble3DSeriesView() {
            InitializeComponent();
            ActualChart = chart;
        }
    }
}
