Imports System.Windows.Controls
Imports DevExpress.Xpf.DemoBase

Namespace SchedulingDemo
    <NoAutogeneratedCodeFiles, CodeFiles("Modules/AboutView.xaml", "ViewModels/LinksViewModel.(cs)")>
    Partial Public Class AboutView
        Inherits UserControl

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
