Imports System.Collections.Specialized
Imports System.Linq
Imports System.Windows
Imports DevExpress.Xpf.DemoBase
Imports DevExpress.Xpf.Scheduling
Imports SchedulingDemo.ViewModels

Namespace SchedulingDemo
    <NoAutogeneratedCodeFiles, CodeFiles("Modules/OutlookInspired/OutlookInspiredDemoModule.xaml", "ViewModels/OutlookInspired/OutlookInspiredDemoViewModel.(cs)")>
    Partial Public Class OutlookInspiredDemoModule
        Inherits SchedulingDemoModule

        Public Sub New()
            MyBase.New(True, True)
            InitializeComponent()
            AddHandler Me.scheduler.SelectedAppointments.CollectionChanged, AddressOf SelectedAppointmentsCollectionChanged
        End Sub

        Private Sub SelectedAppointmentsCollectionChanged(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
            Dim viewModel As OutlookInspiredDemoViewModel = TryCast(DataContext, OutlookInspiredDemoViewModel)
            If viewModel Is Nothing Then
                Return
            End If
            viewModel.SelectedAppointment = If(Me.scheduler.SelectedAppointments.Count = 0, Nothing, Me.scheduler.SelectedAppointments(0))
        End Sub

        Protected Overrides Sub Hide()
            Me.ribbonControl.CloseApplicationMenu()
            MyBase.Hide()
        End Sub

        Private Sub InitNewAppointment(ByVal sender As Object, ByVal e As AppointmentItemEventArgs)
            If e.Appointment.CustomFields("Priority") Is Nothing Then
                e.Appointment.CustomFields("Priority") = EventPriority.None
            End If
            If e.Appointment.CustomFields("IsPrivate") Is Nothing Then
                e.Appointment.CustomFields("IsPrivate") = False
            End If
        End Sub
        Private Sub OnAppointmentWindowShowing(ByVal sender As Object, ByVal e As AppointmentWindowShowingEventArgs)
            e.Window.DataContext = OutlookEventWindowViewModel.Create(Me.scheduler, e.Appointment)
        End Sub

        Private Sub OnCreateResourceSourceObject(ByVal sender As Object, ByVal e As CreateResourceSourceObjectEventArgs)
            e.SourceObject = Calendar.Create()
        End Sub
    End Class
End Namespace
