Imports DevExpress.Xpf.DemoBase

Namespace ControlsDemo.TabControl.Views
    <NoAutogeneratedCodeFiles, CodeFiles("Modules/TabControl.Views/MainView.xaml", "Modules/TabControl.Views/MainViewModel.(cs)")>
    Partial Public Class MainView
        Inherits ControlsDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
