using DevExpress.Xpf.DemoBase;

namespace SchedulingDemo {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/AppointmentCustomizationDemoModule.xaml",
        "ViewModels/AppointmentCustomizationDemoViewModel.(cs)")]
    public partial class AppointmentCustomizationDemoModule : SchedulingDemoModule {
        public AppointmentCustomizationDemoModule() {
            InitializeComponent();
        }
    }
}
