using DevExpress.Xpf.DemoBase;

namespace SchedulingDemo {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/DayViewPerformanceDemoModule.xaml",
        "ViewModels/DayViewPerformanceDemoViewModel.(cs)")]
    public partial class DayViewPerformanceDemoModule : SchedulingDemoModule {
        public DayViewPerformanceDemoModule() {
            InitializeComponent();
        }
    }    
}
