using DevExpress.Xpf.DemoBase;

namespace SchedulingDemo {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/DayViewDemoModule.xaml",
        "ViewModels/DayViewDemoViewModel.(cs)")]
    public partial class DayViewDemoModule : SchedulingDemoModule {
        public DayViewDemoModule() {
            InitializeComponent();
        }
    }
}
