using DevExpress.Xpf.DemoBase;

namespace SchedulingDemo {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/EndUserRestrictionsDemoModule.xaml",
        "Modules/EndUserRestrictionsDemoModule.xaml.(cs)",
        "ViewModels/EndUserRestrictionsDemoViewModel.(cs)")]
    public partial class EndUserRestrictionsDemoModule : SchedulingDemoModule {
        public EndUserRestrictionsDemoModule() {
            InitializeComponent();
        }
    }
}
