using DevExpress.Xpf.DemoBase;

namespace SchedulingDemo {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/MonthViewPerformanceDemoModule.xaml",
        "ViewModels/MonthViewPerformanceDemoViewModel.(cs)")]
    public partial class MonthViewPerformanceDemoModule : SchedulingDemoModule {
        public MonthViewPerformanceDemoModule() {
            InitializeComponent();
        }
    }
}
