using DevExpress.Xpf.DemoBase;

namespace SchedulingDemo {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/MonthViewDemoModule.xaml",
        "ViewModels/MonthViewDemoViewModel.(cs)")]
    public partial class MonthViewDemoModule : SchedulingDemoModule {
        public MonthViewDemoModule() {
            InitializeComponent();
        }
    }
}
