using DevExpress.Xpf.Core;
using DevExpress.Xpf.DemoBase;

namespace SchedulingDemo {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/TimelineViewPerformanceDemoModule.xaml",
        "ViewModels/TimelineViewPerformanceDemoViewModel.(cs)")]
    public partial class TimelineViewPerformanceDemoModule : SchedulingDemoModule {
        public TimelineViewPerformanceDemoModule() {
            InitializeComponent();
        }
    }    
}
