using DevExpress.Xpf.Core;
using DevExpress.Xpf.DemoBase;

namespace SchedulingDemo {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/TimelineScalesDemoModule.xaml",
        "ViewModels/TimelineScalesDemoViewModel.(cs)")]
    public partial class TimelineScalesDemoModule : SchedulingDemoModule {
        public TimelineScalesDemoModule() {
            InitializeComponent();
        }
    }
}
