using DevExpress.Xpf.Core;
using DevExpress.Xpf.DemoBase;

namespace SchedulingDemo {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/TimelineViewDemoModule.xaml",
        "ViewModels/TimelineViewDemoViewModel.(cs)")]
    public partial class TimelineViewDemoModule : SchedulingDemoModule {
        public TimelineViewDemoModule() {
            InitializeComponent();
        }
    }
}
