using DevExpress.Xpf.DemoBase;

namespace SchedulingDemo {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/TimeRulerDemoModule.xaml",
        "ViewModels/TimeRulerDemoViewModel.(cs)")]
    public partial class TimeRulerDemoModule : SchedulingDemoModule {
        public TimeRulerDemoModule() {
            InitializeComponent();
        }
    }
}
