using DevExpress.Xpf.DemoBase;

namespace SchedulingDemo {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/WeekViewDemoModule.xaml",
        "ViewModels/WeekViewDemoViewModel.(cs)")]
    public partial class WeekViewDemoModule : SchedulingDemoModule {
        public WeekViewDemoModule() {
            InitializeComponent();
        }
    }
}
