using DevExpress.Xpf.DemoBase;

namespace SchedulingDemo {
    [NoAutogeneratedCodeFiles, CodeFiles(
        "Modules/WorkWeekViewDemoModule.xaml",
        "ViewModels/WorkWeekViewDemoViewModel.(cs)")]
    public partial class WorkWeekViewDemoModule : SchedulingDemoModule {
        public WorkWeekViewDemoModule() {
            InitializeComponent();
        }
    }
}
