Imports DevExpress.Xpf.DemoBase

Namespace ControlsDemo.TabControl.CustomTheme
    <NoAutogeneratedCodeFiles, CodeFiles("Modules/TabControl.CustomTheme/MainView.xaml", "Modules/TabControl.CustomTheme/MainViewModel.(cs)")>
    Partial Public Class MainView
        Inherits ControlsDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
