Imports DevExpress.Xpf.Core
Imports DevExpress.Xpf.DemoBase

Namespace CommonDemo.TabControl.WebBrowser
    <NoAutogeneratedCodeFiles, CodeFiles("Modules/TabControl.WebBrowser/MainView.xaml", "Modules/TabControl.WebBrowser/MainViewModel.(cs)", "Modules/TabControl.WebBrowser/WebBrowserView.xaml", "Modules/TabControl.WebBrowser/WebBrowserViewModel.(cs)")>
    Partial Public Class MainView
        Inherits DemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
