Imports System
Imports DevExpress.Xpf.Charts
Imports DevExpress.Xpf.DemoBase

Namespace ChartsDemo
    <NoAutogeneratedCodeFiles, CodeFile("Modules/XyzChart/Bubble3DSeriesView.xaml"), CodeFile("Modules/XyzChart/Bubble3DSeriesView.xaml.(cs)")>
    Partial Public Class Bubble3DSeriesView
        Inherits ChartsDemoModule

        Public Sub New()
            InitializeComponent()
            ActualChart = chart
        End Sub
    End Class
End Namespace
