Imports DevExpress.Xpf.DemoBase

Namespace DockingDemo
    <NoAutogeneratedCodeFiles, CodeFiles("Modules/ColorizedTabs.xaml", "ViewModels/ColorizedTabsViewModel.(cs)")>
    Partial Public Class ColorizedTabs
        Inherits DockingDemoModule

        Public Sub New()
            InitializeComponent()
        End Sub
    End Class
End Namespace
